#!/usr/bin/env bash

_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

# shellcheck source=./lib/helpers
source "$_dir"/helpers

# shellcheck disable=SC2119
request-sudo

if [[ "$SHELL" != *zsh ]]; then
	message "changing default shell to Zsh..."
	zsh_path="$(command -v zsh)"

	if is-macos; then
		request-sudo chsh -s "$zsh_path" "$USER"
	else
		if ! grep 'zsh' /etc/shells >/dev/null; then
			message "adding Zsh to /etc/shells..."
			echo "$zsh_path" | request-sudo tee -a /etc/shells
			message "done adding Zsh to /etc/shells."
		fi
		chsh --shell "$zsh_path"
	fi

	message "done changing default shell to Zsh."
fi

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Clone powerlevel10k ZSH theme
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

message "initializing Zsh configuration..."
data_dir="$(xdg_data)"/zsh
if ! [ -d "$data_dir" ]; then
	mkdir -p "$data_dir"
fi
ln -sf "$_dir"/../zsh/* "$data_dir"
ln -sf "$_dir"/../.zshrc "$HOME"
message "done initializing Zsh configuration."
